# Generated by Django 3.1.4 on 2021-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20201217_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='updated_at',
            new_name='fechaApartura',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='fechaApertura',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo'), ('separado', 'Separado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipoCuenta',
            field=models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente'), ('programado', 'Programado')], default='ahorros', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(default='descripcion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'Deposito'), ('retiro', 'Retiro')], default='deposito', max_length=20),
        ),
    ]
